apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::356855127197ser/github-actions-deploy
      username: github-actions-deploy
      groups:
        - system:masters
